theRouteManager/routeManager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from . import api
from .views import authentication_views, location_views, page_views, routing_views

BASE_ROUTE = "routeManager"


urlpatterns = [
    path("admin/", admin.site.urls),
    # Password reset
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/",
        authentication_views.password_reset_view,
        name="password_reset",
    ),
    path("password_reset/done/", page_views.home_view, name="password_reset_done"),
    path("reset/done/", page_views.home_view, name="password_reset_complete"),
    # Register
    path(
        f"{BASE_ROUTE}/register",
        authentication_views.account_create_view,
        name="register",
    ),
    ### VIEWS ###
    # Home and logins
    path(f"{BASE_ROUTE}/home", page_views.home_view, name="home"),
    path(f"{BASE_ROUTE}/", authentication_views.login_view, name="login"),
    path(f"{BASE_ROUTE}/logout", authentication_views.logout_view, name="logout"),
    # Location
    path(
        f"{BASE_ROUTE}/add_loc_view", location_views.add_loc_view, name="add_loc_view"
    ),
    path(
        f"{BASE_ROUTE}/lookup_loc", location_views.display_locations, name="lookup_loc"
    ),
    # Plan
    path(f"{BASE_ROUTE}/view_plans", page_views.view_plans, name="view_plans"),
    path(f"{BASE_ROUTE}/planner", routing_views.planner, name="planner"),
    path(f"{BASE_ROUTE}/planner/<int:id>/", routing_views.planner, name="planner"),
    # Logs
    path(f"{BASE_ROUTE}/view_logs", page_views.view_logs, name="view_logs"),
    ###########
    ### API ###
    ###########
    # Bookmark API
    path(
        f"{BASE_ROUTE}/bookmark_location",
        api.bookmark_location,
        name="bookmark_location",
    ),
    # Location API
    path(f"{BASE_ROUTE}/search", api.search_loc, name="search"),
    path(
        f"{BASE_ROUTE}/delete_location/<int:location_id>/",
        api.delete_location,
        name="delete_location",
    ),
    path(
        f"{BASE_ROUTE}/edit_location/<int:location_id>/",
        location_views.edit_loc_view,
        name="edit_location",
    ),
    path(
        f"{BASE_ROUTE}/get_location_names",
        api.get_location_names,
        name="get_location_names",
    ),
    # Note API
    path(f"{BASE_ROUTE}/fetch_notes", api.fetch_notes, name="fetch_notes"),
    path(f"{BASE_ROUTE}/add_note", api.add_note, name="add_note"),
    path(
        f"{BASE_ROUTE}/delete_note/<int:note_id>/", api.delete_note, name="delete_note"
    ),
    # Plan API
    path(f"{BASE_ROUTE}/save_route", api.save_route, name="save_route"),
    path(
        f"{BASE_ROUTE}/planner/<int:id>/save_route", api.save_route, name="save_route"
    ),
    path(
        f"{BASE_ROUTE}/get_plan_route/<int:plan_id>/",
        api.get_plan_route,
        name="get_plan_route",
    ),
    path(
        f"{BASE_ROUTE}/delete_route/<int:plan_id>/",
        api.delete_route,
        name="delete_route",
    ),
    path(
        f"{BASE_ROUTE}/update_plan_status/<int:plan_id>/",
        api.update_plan_status,
        name="update_plan_status",
    ),
]

theRouteManager/theRouteManager/urls.py
from django.urls import include, path

urlpatterns = [path("", include("routeManager.urls"))]

theRouteManager/routeManager/models.py
import numpy as np
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import JSONField, Q

from .calculations import calculate_ball_tree, nearest_loc_index
from .utilities.utils import generate_ssn, generate_username, process_json


class ROLE(models.TextChoices):
    OWNER = "ownr", "Owner"
    MANAGER = "mngr", "Manager"
    OPERATOR = "oper", "Operator"


class STATUS(models.TextChoices):
    PENDNG = "pendng", "Pending"
    ACCEPT = "accept", "Accepted"
    REJECT = "reject", "Rejected"
    CANCEL = "cancel", "Canceled"
    PROGRS = "progrs", "In-progress"
    COMPLT = "complt", "Complete"


STATUS_VALID_VALUES = dict(STATUS.choices)


class PLAN_CLEARANCE(models.TextChoices):
    CONFIDENTIAL = "cfdt", "Is confidential"
    OPEN = "open", "Is open"


class ACTION(models.TextChoices):
    CREATE = "crt", "Created"
    UPDATE = "upd", "Updated"
    DELETE = "del", "Deleted"
    LOGIN = "lgn", "Logged In"
    LOGOUT = "lgt", "Logged Out"
    NONE = "non", "None"


class PERMISSIONS:
    CAN_CREATE_ACCOUNT = "can_create_acc"
    CAN_ADD_LOC = "can_add_loc"
    CAN_EDIT_LOC = "can_edit_loc"
    CAN_DELETE_LOC = "can_delete_loc"

    CAN_ADD_PLAN = "can_add_route"
    CAN_EDIT_PLAN = "can_edit_plan"
    CAN_DELETE_PLAN = "can_edit_plan"
    CAN_VIEW_PLAN = "can_view_plan"
    CAN_UPDATE_PLAN_STATUS = "can_update_plan_status"

    CAN_ADD_NOTE = "can_add_note"
    CAN_EDIT_NOTE = "can_edit_note"
    CAN_DELETE_NOTE = "can_delete_note"

    CAN_UN_BOOKMARK = "can_un_bookmark"

    UNIVERSAL_PERMS = [CAN_ADD_LOC, CAN_ADD_PLAN, CAN_ADD_NOTE, CAN_EDIT_LOC]


class JSON_FIELDS:
    LOCATION = ["lat", "lng", "name", "address", "location_type"]
    PLAN = ["plan_name", "est_distance", "est_duration", "route_data"]


class MyAccountManager(BaseUserManager):
    def create_user(
        self,
        email: str | None = None,
        password: str | None = None,
        full_name: str | None = None,
        username: str | None = None,
        user_role: tuple[str, str] | None = None,
        ssn: str | None = None,
    ) -> "Account":
        """Create and return a new user."""
        if not email:
            raise ValueError("Users must have an email address")

        if username is None:
            username = generate_username(email)
        if user_role is None:
            user_role = ROLE.OPERATOR
        if ssn is None:
            ssn = generate_ssn()

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            full_name=full_name,
            ssn=ssn,
            user_role=user_role,
        )

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(
        self, email=None, username: str | None = None, password: str | None = None
    ) -> "Account":
        """Create and return a new superuser."""
        if username is None:
            username = "godmode"

        if password is None:
            raise ValueError("Superusers must have a password")

        email = f"{username}@superuser.com"
        ssn = generate_ssn()
        user = self.create_user(email, password, username, username, ROLE.OWNER, ssn)
        user.is_admin = user.is_staff = user.is_superuser = user.is_active = True
        user.save(using=self._db)

        return user


class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(verbose_name="username", max_length=20, unique=True)
    full_name = models.CharField(
        verbose_name="full name", max_length=60, unique=False, null=True
    )
    ssn = models.CharField(verbose_name="ssn", max_length=9, unique=True, null=True)

    user_role = models.CharField(
        max_length=4, choices=ROLE.choices, default=ROLE.OPERATOR
    )

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)  # False in production
    is_staff = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = MyAccountManager()

    USERNAME_FIELD = "username"

    def __repr__(self) -> str:
        return f"{self.username} [{self.user_role}] | {self.email} | {self.full_name} | {self.ssn}"

    def __str__(self):
        return self.__repr__()

    def has_perm(self, perm, obj=None):
        """Check if the user has a specific permission."""

        if self.user_role == ROLE.OWNER:
            return True

        if perm in PERMISSIONS.UNIVERSAL_PERMS:
            return True

        if isinstance(obj, Plan) and (output := self._plan_perms(perm, obj)):
            return output

        if isinstance(obj, Note):
            print(obj.author)
            print(self)
            if (
                perm in [PERMISSIONS.CAN_EDIT_NOTE, PERMISSIONS.CAN_DELETE_NOTE]
                and obj.author == self
            ):
                return True

        if perm == PERMISSIONS.CAN_UN_BOOKMARK and isinstance(obj, Bookmark):
            return obj.user == self

        if self.user_role == ROLE.MANAGER:
            return perm in [
                # Location
                PERMISSIONS.CAN_DELETE_LOC,
            ]

        return False

    def has_module_perms(self, app_label):
        """Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)"""
        return True

    def _plan_perms(self, perm, obj: "Plan"):
        if (
            perm == PERMISSIONS.CAN_VIEW_PLAN
            and self.user_role == ROLE.OPERATOR
            and obj.clearance == PLAN_CLEARANCE.OPEN
        ):
            return True

        if perm == PERMISSIONS.CAN_EDIT_PLAN and obj.status == STATUS.PENDNG:
            return self.user_role == ROLE.MANAGER or obj.user == self

        if perm == PERMISSIONS.CAN_UPDATE_PLAN_STATUS:
            return obj.status != STATUS.COMPLT and self.user_role == ROLE.MANAGER

        if perm == PERMISSIONS.CAN_DELETE_PLAN:
            if self.user_role == ROLE.MANAGER:
                return obj.status != STATUS.COMPLT

        return None


class Location(models.Model):
    location_id = models.AutoField(primary_key=True)
    lat = models.FloatField()
    lng = models.FloatField()
    name = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    location_type = models.CharField(max_length=255, blank=True, null=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"({self.lat}, {self.lng}) {self.name} @ {self.address}"

    def is_bookmarked_by(self, user: Account | None = None):
        if user is None:
            return False
        return Bookmark.objects.filter(user=user, location=self).exists()

    def serialize(self, user):
        return {
            "pk": str(self.pk),
            "lat": self.lat,
            "lng": self.lng,
            "name": self.name,
            "address": self.address,
            "location_type": self.location_type,
            "is_bookmarked": self.is_bookmarked_by(user),
            "modified_at": self.modified_at,
        }

    @staticmethod
    def get_nearest(lat, lng, max_distance_meters=200):
        locations = list(Location.objects.all())
        location_coords = np.radians(
            [(location.lat, location.lng) for location in locations]
        )

        tree = calculate_ball_tree(location_coords)
        distances, indices = tree.query(
            [np.radians([float(lat), float(lng)])], return_distance=True
        )

        nearest_index = nearest_loc_index(distances, indices, max_distance_meters)
        if nearest_index is not None:
            return locations[nearest_index]
        return None

    @staticmethod
    def parse_osm_route(route_data):
        waypoints = route_data[0]["waypoints"]
        waypoint_coords = [
            (waypoint["latLng"]["lat"], waypoint["latLng"]["lng"])
            for waypoint in waypoints
        ]
        locations_waypoints = []
        for lat, lng in waypoint_coords:
            found_location = Location.get_nearest(lat, lng)
            if isinstance(found_location, Location):
                locations_waypoints.append((found_location.location_id, 1))
            else:
                locations_waypoints.append(((lat, lng), -1))

        return locations_waypoints

    @staticmethod
    def create_from_json(data):
        try:
            return Location(**process_json(data, JSON_FIELDS.LOCATION))
        except Exception as e:
            print(e)
            return None


class Bookmark(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __repr__(self):
        return (
            f"{self.user.username} bookmarked {self.location.name} @ {self.created_at}"
        )

    def __str__(self):
        return self.__repr__()

    @staticmethod
    def get_bookmarked_locations(user, n=None, query="", sort_bookmark=False):
        if query:
            locations = Location.objects.filter(
                Q(name__icontains=query) | Q(address__icontains=query)
            )
        else:
            locations = Location.objects.all()

        locations = locations.order_by("-modified_at")
        loc_w_bookmark = [loc.serialize(user) for loc in locations]
        loc_w_bookmark.sort(key=lambda x: x["modified_at"], reverse=True)
        if sort_bookmark:
            # If sort_bookmark is True, sort by is_bookmarked first and then by date modified
            loc_w_bookmark.sort(key=lambda x: x["is_bookmarked"], reverse=True)

        # Limit the number of locations returned
        if n is not None:

theRouteManager/routeManager/views/location_views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from ..forms import EditLocationForm
from ..models import PERMISSIONS, Location, LoggerSystem
from ..utilities.json_utils import (
    JSON_INSUFFICIENT_PERMISSION,
    json_return_error_status,
    json_return_success_status,
)


@login_required(login_url="home")
def display_locations(request):
    return render(request, "lookup_loc.html")


@login_required(login_url="home")
def add_loc_view(request):
    if request.user.has_perm(PERMISSIONS.CAN_ADD_LOC):
        if request.method == "POST":
            data = json.loads(request.body)
            location = Location.create_from_json(data)
            if location:
                location.save()
                new_log = LoggerSystem.create_add_loc_log(request.user, location)
                new_log.save()
                print(new_log)
                return JsonResponse(json_return_success_status("Location", "added"))
        return render(request, "add_loc.html")
    return JsonResponse(JSON_INSUFFICIENT_PERMISSION)


@login_required(login_url="home")
def edit_loc_view(request, location_id):
    print("I am called")
    location = get_object_or_404(Location, pk=location_id)
    
    if not request.user.has_perm(PERMISSIONS.CAN_EDIT_LOC, location):
        return JsonResponse(JSON_INSUFFICIENT_PERMISSION)


    if request.method == "POST":
        old_name = location.name
        old_addr = location.address
        form = EditLocationForm(request.POST, instance=location)
        if form.is_valid():
            message = process_edit_location_form_log(
                request.user, location, form, old_name, old_addr
            )
            return create_edit_loc_form_log(message)
        else:
            return JsonResponse(
                json_return_error_status("Location", "cannot be updated")
            )

    form = EditLocationForm(instance=location)
    form_html = form_html_builder(
        "editLocationForm", f"edit_location/{location_id}/", form
    )
    return JsonResponse({"form_html": form_html})


def form_html_builder(id, action, form):
    return f'<form id="{id}" action="{action}" method="post">{form.as_p()}</form>'


def process_edit_location_form_log(user, location, form, old_name, old_addr):
    new_name = form.cleaned_data.get("name")
    new_addr = form.cleaned_data.get("address")
    message = []
    if new_name != old_name:
        message.append("name")
        create_edit_loc_log(user, location, "name", old_name, new_name)
    if new_addr != old_addr:
        message.append("address")
        create_edit_loc_log(user, location, "address", old_addr, new_addr)
    form.save()
    return message


def create_edit_loc_form_log(message):
    if len(message) == 0:
        return JsonResponse(
            json_return_success_status("Location data same,", "nothing was updated")
        )
    if len(message) == 1:
        message = message[0]
    else:
        message = " and ".join(message)
    return JsonResponse(json_return_success_status(f"Location {message}", "updated"))


def create_edit_loc_log(user, location, field, old_val, new_val):
    """Create an edit location log for the given user and location and what is changed."""
    new_log = LoggerSystem.create_edit_loc_log(
        user=user,
        location=location,
        field_name=field,
        old_value=old_val,
        new_value=new_val,
    )
    new_log.save()
    print(new_log)

theRouteManager/routeManager/views/page_views.py
import json

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from ..models import Log, Plan


def home_view(request):
    return render(request, "home.html")


@login_required(login_url="home")
def view_logs(request):
    logs = Log.objects.all().order_by("-timestamp")
    return render(request, "view_logs.html", {"logs": logs})


@login_required(login_url="home")
def view_plans(request):
    return render(
        request,
        "view_plans.html",
        {"plans_json": json.dumps(Plan.get_plans()), "current_user": request.user},
    )

theRouteManager/routeManager/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Thank you for creating an account. Please click the link below to verify your email address and complete the registration process:

{{ password_reset_link }}

If you didn't create an account, you can ignore this email.

Thanks,
Your Team
{% endautoescape %}

theRouteManager/routeManager/templates/add_loc.html
{% extends "main/appheader.html" %}
{% load static %}
{% block afterlogin %}

<!-- Page Title -->
<h1 class="mb-3">Add location</h1>

<!-- Map Display -->
<div id="map_display" class="card" style="height: 80vh;">
    <!-- Search Box -->
    <div class="card-header">
        <input id="search" type="text" class="form-control" placeholder="Search for a location">
    </div>
    <!-- Map -->
    <div id="osm-map" class="card-body" style="height: 70vh;"></div>
    <!-- Save Button -->
    <div class="card-footer">
        <button id="save-location" class="btn btn-primary">Save Location</button>
    </div>
</div>

<script>
    var map;
    var selectedLocation = null;
</script>

<link rel="stylesheet" href="{% static 'routeManager/css/add_loc_style.css' %}" />

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>

<script src="{% static 'routeManager/js/common.js' %}"></script>
<script src="{% static 'routeManager/js/ajax_common.js' %}"></script>
<script src="{% static 'routeManager/js/getmap.js' %}"></script>

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />

{% endblock afterlogin %}

theRouteManager/routeManager/templates/home.html
{% extends "main/appheader.html" %}
{% block afterlogin %}
<h1 class="display-5">Welcome to the Home Page!</h1>

{% if user.is_authenticated %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Hello, {{ user.username }}!</h5>
        <p class="card-text">You are logged in.</p>
        <p class="card-text">Your role is: {{ user.get_user_role_display }}</p>
        <p class="card-text">Your email is: {{ user.email }}</p>
        <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
    </div>
</div>
{% else %}
<p class="lead">You are not logged in.</p>
<hr class="my-4">
<p><a href="{% url 'login' %}" role="button">Login</a> or ask an authorized user to create your account</p>
{% endif %}
{% endblock afterlogin %}

theRouteManager/routeManager/templates/login.html
{% extends "main/header.html" %}

{% block content %}
<h2 class="mb-3">Login</h2>
<form method="post" class="needs-validation" novalidate>
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" class="btn btn-primary">Login</button>
</form>
<p class="mt-3">If you forgot your password, <a href="{% url 'password_reset' %}">recover your account here</a>.</p>
{% endblock %}

theRouteManager/routeManager/templates/lookup_loc.html
{% extends "main/appheader.html" %}
{% load static %}
{% block afterlogin %}

<!-- Stylesheet -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">

<!-- Page Title -->
<h1 class="mb-3">Lookup Locations</h1>

<!-- Search Box -->
<div class="input-group mb-3">
    <input type="text" id="searchBox" class="form-control" placeholder="Search locations...">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
    <div class="input-group-append">
        <button id="searchAllButton" class="btn btn-primary" type="button">View all locations</button>
    </div>
</div>

<!-- Location Table -->
<p id="locationCount"></p>
<table id="locationTable" class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th id='loc-table-name' style='width: 10%'>Location Name</th>
            <th id='loc-table-address' style='width: 20%'>Location Address</th>
            <th id='loc-table-modify-date' style='width: 10%'>Modified at</th>
            <th id='loc-table-view-note-button' style='width: 25%'></th>
        </tr>
    </thead>
    <tbody id="locationList">
        <!-- The locations will be populated here by the AJAX call -->
    </tbody>

</table>

<!-- Add Note Modal -->
{% include "modal/add_note.html" %}

<!-- View Notes Modal -->
{% include "modal/view_notes.html" %}

<!-- Edit Location Modal -->
{% include "modal/edit_loc.html" %}

<style>

</style>

<script>
    const searchURL = '{% url "search" %}';
    const fetchNotesURL = '{% url "fetch_notes" %}';
    const addNoteURL = '{% url "add_note" %}';
    const bookmarkURL = '{% url "bookmark_location" %}';
    const username = '{{user.username}}';
</script>

<!-- Scripts -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<script src="{% static 'routeManager/js/common.js' %}"></script>
<script src="{% static 'routeManager/js/ajax_common.js' %}"></script>
<script src="{% static 'routeManager/js/lookup.js' %}"></script>

{% endblock afterlogin %}

theRouteManager/routeManager/templates/password_reset.html
{% extends "main/header.html" %}

{% block content %}
<h2 class="text-center">Reset Your Password</h2>
<form method="post" class="form-group">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Request Password Reset</button>
</form>
{% endblock %}

theRouteManager/routeManager/templates/password_reset_confirm.html
{% extends "main/header.html" %}

{% block content %}
<h2 class="text-center">Reset Your Password</h2>
<form method="post" class="form-group">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Request Password Reset</button>
</form>
{% endblock %}

theRouteManager/routeManager/templates/password_reset_email.html
{% autoescape off %}
Hi {{ user.full_name }},

You requested a password reset. Please click the link below to reset your password:

{{ password_reset_link }}

If you didn't request this, you can ignore this email.

Thanks,
Your Team
{% endautoescape %}

theRouteManager/routeManager/templates/register.html
{% extends "main/header.html" %}

{% block content %}
<h2 class="mb-3">Register</h2>
<form method="post" class="needs-validation" novalidate>
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" class="btn btn-primary">Register</button>
</form>
<p class="mt-3">If you already have an account, <a href="{% url 'login' %}">login here</a>.</p>
{% endblock %}

theRouteManager/routeManager/templates/view_logs.html
{% extends 'main/appheader.html' %}

{% block afterlogin %}
<h1 class="my-4">Logs</h1>
<div class="table-responsive" style="max-height: 80vh;">
    <table class="table table-striped">
        <thead class="thead-dark sticky-top">
            <tr>
                <th scope="col" style="width: 10%;">Username</th>
                <th scope="col" style="width: 10%;">Role</th>
                <th scope="col" style="width: 10%;">Action</th>
                <th scope="col" style="width: 10%;">Object</th>
                <th scope="col" style="width: 15%;">Timestamp</th>
                <th scope="col" style="width: 15%;">Field changed</th>
                <th scope="col" style="width: 15%;">Old value</th>
                <th scope="col" style="width: 15%;">New value</th>
            </tr>
        </thead>
        <tbody>
            {% for log in logs %}
            <tr>
                <td>{{ log.user.username }}</td>
                <td>
                    <span
                        class="badge {% if log.user.get_user_role_display == 'Owner' %}badge-primary{% elif log.user.get_user_role_display == 'Manager' %}badge-success{% else %}badge-info{% endif %}">
                        {{ log.user.get_user_role_display }}
                    </span>
                </td>
                <td>
                    <span
                        class="badge {% if log.get_action_display == 'Created' %}badge-success{% elif log.get_action_display == 'Updated' %}badge-warning{% elif log.get_action_display == 'Deleted' %}badge-danger{% elif log.get_action_display == 'Logged In' %}badge-primary{% elif log.get_action_display == 'Logged Out' %}badge-secondary{% else %}badge-light{% endif %}">
                        {{ log.get_action_display }}
                    </span>
                </td>
                <td>{{ log.content_type.model|capfirst }}</td>
                <td>{{ log.timestamp }}</td>
                <td>{{ log.field_name }}</td>
                <td>{{ log.old_value }}</td>
                <td>{{ log.new_value }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}